function Hd = EllipticBandPass
%ELLIPTICBANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 11-Apr-2020 18:07:54

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 100000;  % Sampling Frequency

Fstop1 = 15000;   % First Stopband Frequency
Fpass1 = 20000;   % First Passband Frequency
Fpass2 = 30000;   % Second Passband Frequency
Fstop2 = 35000;   % Second Stopband Frequency
Astop1 = 50;      % First Stopband Attenuation (dB)
Apass  = 5;       % Passband Ripple (dB)
Astop2 = 50;      % Second Stopband Attenuation (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);



% [EOF]
